[2024-03-29T01:53:53.671+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount permission to 509
[2024-03-29T01:53:53.672+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount'
[2024-03-29T01:53:53.697+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount permission to 509
[2024-03-29T01:53:53.698+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount'
[2024-03-29T01:53:53.743+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_kubernetes_executor.test_sharedvolume_mount manual__2024-03-29T01:53:37.362760+00:00 [queued]>
[2024-03-29T01:53:53.769+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_kubernetes_executor.test_sharedvolume_mount manual__2024-03-29T01:53:37.362760+00:00 [queued]>
[2024-03-29T01:53:53.770+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-03-29T01:53:53.790+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): test_sharedvolume_mount> on 2024-03-29 01:53:37.362760+00:00
[2024-03-29T01:53:53.800+0000] {standard_task_runner.py:57} INFO - Started process 117 to run task
[2024-03-29T01:53:53.804+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_kubernetes_executor', 'test_sharedvolume_mount', 'manual__2024-03-29T01:53:37.362760+00:00', '--job-id', '8', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/example_kubernetes_executor.py', '--cfg-path', '/tmp/tmp7i30dpsb']
[2024-03-29T01:53:53.807+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask test_sharedvolume_mount
[2024-03-29T01:53:53.966+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount permission to 509
[2024-03-29T01:53:53.967+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=test_sharedvolume_mount'
[2024-03-29T01:53:53.974+0000] {task_command.py:415} INFO - Running <TaskInstance: example_kubernetes_executor.test_sharedvolume_mount manual__2024-03-29T01:53:37.362760+00:00 [running]> on host 1279dfb12ee8
[2024-03-29T01:53:54.085+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_kubernetes_executor' AIRFLOW_CTX_TASK_ID='test_sharedvolume_mount' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T01:53:37.362760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T01:53:37.362760+00:00'
[2024-03-29T01:53:54.105+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-29T01:53:54.126+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=example_kubernetes_executor, task_id=test_sharedvolume_mount, execution_date=20240329T015337, start_date=20240329T015353, end_date=20240329T015354
[2024-03-29T01:53:54.177+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-29T01:53:54.216+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
