[2024-03-29T01:53:49.491+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task permission to 509
[2024-03-29T01:53:49.493+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task'
[2024-03-29T01:53:49.541+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task permission to 509
[2024-03-29T01:53:49.542+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task'
[2024-03-29T01:53:49.607+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_kubernetes_executor.other_namespace_task manual__2024-03-29T01:53:37.362760+00:00 [queued]>
[2024-03-29T01:53:49.623+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_kubernetes_executor.other_namespace_task manual__2024-03-29T01:53:37.362760+00:00 [queued]>
[2024-03-29T01:53:49.624+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-03-29T01:53:49.642+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): other_namespace_task> on 2024-03-29 01:53:37.362760+00:00
[2024-03-29T01:53:49.657+0000] {standard_task_runner.py:57} INFO - Started process 104 to run task
[2024-03-29T01:53:49.664+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'example_kubernetes_executor', 'other_namespace_task', 'manual__2024-03-29T01:53:37.362760+00:00', '--job-id', '6', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/example_kubernetes_executor.py', '--cfg-path', '/tmp/tmphx7tmr_3']
[2024-03-29T01:53:49.675+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask other_namespace_task
[2024-03-29T01:53:49.883+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task permission to 509
[2024-03-29T01:53:49.884+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=example_kubernetes_executor/run_id=manual__2024-03-29T01:53:37.362760+00:00/task_id=other_namespace_task'
[2024-03-29T01:53:49.887+0000] {task_command.py:415} INFO - Running <TaskInstance: example_kubernetes_executor.other_namespace_task manual__2024-03-29T01:53:37.362760+00:00 [running]> on host 1279dfb12ee8
[2024-03-29T01:53:50.029+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_kubernetes_executor' AIRFLOW_CTX_TASK_ID='other_namespace_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T01:53:37.362760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T01:53:37.362760+00:00'
[2024-03-29T01:53:50.053+0000] {logging_mixin.py:151} INFO - annotated!
[2024-03-29T01:53:50.054+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-29T01:53:50.075+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=example_kubernetes_executor, task_id=other_namespace_task, execution_date=20240329T015337, start_date=20240329T015349, end_date=20240329T015350
[2024-03-29T01:53:50.257+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-29T01:53:50.404+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
